### ISSUE TITLE
ILI9341 Colors invertet / no Audio on I2S Pins GP26/27/28

### ISSUE THREAD

**Issue by SRDWA** [pondahai/rp2040-doom-ili9341#2]
Hello, unfortunately I have a problem with my SPI ILI9341 **3.2"** display (Black PCB). The image (the colors) are inverted. I took a screenshot and then inverted it in a graphics program, then the colors are correct.

The second problem I have is that no digital audio is coming out of the I2S pins. Have you disabled the digital audio output?
I saw that you placed the "BACK" button on GP28. Is there a conflict there?

Unfortunately I have no idea about compiling. Unfortunately I have to rely on the UF2 images.

**Comment by SRDWA** [comment]
Picture from Display.

![20240817_205112](https://github.com/user-attachments/assets/baeda8d3-a558-402c-9ede-96bb7e12d12b)

**Comment by SRDWA** [comment]
Picture inverted in grafics program.


![20240817_205112](https://github.com/user-attachments/assets/872dd553-a73d-4d18-bfef-74f06f1c5dfc)

**Comment by pondahai** [comment]
首先我解答關於I2S
是得我關閉了I2S 改為使用PWM於 P7
這是因為我要適應我的硬體不得已的做法

螢幕反相的問題請讓我想一想為什麼會這樣
您可以先換另一塊(不同廠牌)LCD試試看
我之前有遇到同樣的晶片編號 但卻是反相的畫面

I've switched to using PWM on pin P7 instead of I2S because my hardware configuration doesn't allow for the change.

Regarding the screen inversion issue, let me know if you have any other ideas and/or want to try different LCDs.
I had a similar experience with a different chip ID but still got an inverted screen.

**Comment by SRDWA** [comment]
Thank you very much for your quick reply. I read that you can invert the display using software. I looked at the "magc.h". This is not possible? See screenshots.

![Screenshot 2024-08-18 105154](https://github.com/user-attachments/assets/583e08a0-11f9-4b72-ac17-4c0025f6f5c9)
![Screenshot 2024-08-18 105500](https://github.com/user-attachments/assets/932a02f7-ce35-4e09-8717-b571cbc228fd)

A second display has been ordered, this time with a red PCB. However, I would like to use the display with the black PCB because it is an IPS screen.

Audio: would it be possible to compile my own binary? I would need the I2S functionality. Since this requires the GP28, you could put the button on a free GPIO, for example GP14.

![Screenshot 2024-08-18 110117](https://github.com/user-attachments/assets/db5c0167-12f2-4bc0-bc2e-2d4efaf9455f)

**Comment by pondahai** [comment]
您提到的這些項目 可能需要您自己嘗試了 抱歉 我目前沒有答案

You may need to try these items yourself. Sorry, I don't have an answer at the moment. ^_^

**Comment by SRDWA** [comment]
The ILI9341 with red PCB (TN display) displays the image correctly. However, the display has a very poor viewing angle.
As I don't have the knowledge to compile the source code, 
I'm now looking for a hardware solution to improve the sound.
Does it make sense to buffer pin 7 and connect an analog amplifier with a real speaker there?
